### DISCUSSION TITLE
Fail-safe to stop charging

### DISCUSSION THREAD

**Discussion by bmesuere** [thomase1234/esphome-fake-xemex-csmb#20] [Q&A]
While this ESPHome project works great, I'm a bit worried about what happens when home assistant crashes for some reason.

If the last set value would be one to increase the current, after a few seconds the wallbox would start charging at maximal current (potentially exceeding the home main fuse limit).

It would therefore be great to have some kind of fail-safe which stops the wallbox (i.e. sets a high ct value) when no value has been set for a certain amount of seconds (a dead man's switch). This is my first time using ESPhome, so any guidance on how to best implement this would be welcome.

**Comment by bmesuere** [comment]
To answer my own question, I have added this to my config:

```yaml
# deadman's switch
interval:
  interval: 20s
  then:
    if:
      condition:
        not:
          api.connected:
      then:
        - logger.log:
            format: No HA connection found, setting current to a safe value.
            level: WARN
        - number.to_max: 
            id: ct1current
```

This will check every 20s if there is at least one client (i.e. HA instance) connected to the API. If not, it will log a warning message and set `ct1current` to max.

In addition, I added `initial_value: 60` to the number configuration itself (the default was 0).
